# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('source_url', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('uri', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
